### ISSUE TITLE
No way to exit authentication/registration flow

### ISSUE THREAD

**Issue by ihh** [GMOD/jbconnect-hook-jblast#109]
There's no way to exit the "register" or "sign in" dialog for that matter. Try entering a wrong password: you get stuck. No ESC to exit or whatever. I have to go back and reload the page.

Incidentally there's some inconsistency in "sign in" vs "log out". It would be better to get these all consistent (e.g. "log in" & "log out")

**Comment by enuggetry** [comment]
Changing to the term "log in"

Summarizing:
Register page needs button to go back to the jbrowse page, if entered from the jbrowse page.  However, if register page is entered from the /login page, that exit button should not be there.  Perhaps the exit button should just be a standard close dialog button, normally an "X" at the upper right.

**Comment by ihh** [comment]
Yes. Or pressing ESC. Either (or both) of those

**Comment by enuggetry** [comment]
Remaining case, URL track appearing with error.  URL tracks that don't exist in the dataset should just not appear.

**Comment by ihh** [comment]
@enuggetry Did you mean to put the above comment on issue #108 and reopen that issue, rather than this one?

**Comment by enuggetry** [comment]
oh yes.
